-- =============================================================================
-- NSTP Portal — Full Targeted Reset
-- Database : nstp_db  (XAMPP / MySQL 5.7+)
-- Author   : Generated by Antigravity — 2026-05-29
--
-- PRESERVES : users WHERE role = 'Admin'
--             Laravel system tables (migrations, cache, jobs, failed_jobs)
--
-- CLEARS    : Every operational table across all three portals
--               Coordinator  — instructors/officers, approvals, calendar,
--                              certificates, sections, students, reports
--               Instructor   — sections, submissions, plans, reports,
--                              announcements, calendar events, classes
--               ROTC Officer — platoons, officer rosters, designs,
--                              submissions, calendar events
-- =============================================================================

USE `nstp_db`;

-- =============================================================================
-- SECTION A — PRE-WIPE VERIFICATION  (run & review BEFORE executing Section B)
-- =============================================================================

-- A1. Admin accounts that MUST survive — confirm at least 1 row appears
SELECT id, full_name, email, role, component, created_at
FROM   `users`
WHERE  `role` = 'Admin';

-- A2. Non-admin accounts that WILL be removed — review carefully
SELECT id, full_name, email, role, component, created_at
FROM   `users`
WHERE  `role` <> 'Admin';

-- A3. Row counts for every table about to be cleared
SELECT 'students'               AS tbl, COUNT(*) AS cnt FROM `students`
UNION ALL
SELECT 'sections',                       COUNT(*) FROM `sections`
UNION ALL
SELECT 'enrollments',                    COUNT(*) FROM `enrollments`
UNION ALL
SELECT 'attendance',                     COUNT(*) FROM `attendance`
UNION ALL
SELECT 'activity_plans',                 COUNT(*) FROM `activity_plans`
UNION ALL
SELECT 'accomplishment_reports',         COUNT(*) FROM `accomplishment_reports`
UNION ALL
SELECT 'activities',                     COUNT(*) FROM `activities`
UNION ALL
SELECT 'announcements',                  COUNT(*) FROM `announcements`
UNION ALL
SELECT 'notifications (non-admin)',      COUNT(*) FROM `notifications`
  WHERE `role` IS NULL OR LOWER(`role`) NOT IN ('admin','administrator')
UNION ALL
SELECT 'portal_audit_logs (non-admin)', COUNT(*) FROM `portal_audit_logs`
  WHERE `role` IS NULL OR LOWER(`role`) NOT IN ('admin','administrator')
UNION ALL
SELECT 'audit_logs (legacy)',            COUNT(*) FROM `audit_logs`;

-- =============================================================================
-- SECTION B — TARGETED WIPE
-- Execute block-by-block, or run the entire section as one transaction.
-- =============================================================================

SET FOREIGN_KEY_CHECKS = 0;

-- ── 1. COORDINATOR PORTAL ────────────────────────────────────────────────────

-- 1a. Instructors & ROTC Officers Section
--     Removes every non-Admin user account (instructors / officers).
--     Admin rows (role = 'Admin') are never touched.
DELETE FROM `users` WHERE `role` <> 'Admin';

-- 1b. Report & Activity Approvals
--     Clears all pending, approved, and rejected approval records stored
--     in the activity_plans and accomplishment_reports tables.
TRUNCATE TABLE `activity_plans`;
TRUNCATE TABLE `accomplishment_reports`;

-- 1c. Activity Calendar
--     Wipes all scheduled events and calendar logs for every component.
TRUNCATE TABLE `activities`;

-- 1d. Certificate Templates
--     If you store certificate templates / batch records in a dedicated
--     table, add it here.  Replace the placeholder name if different.
-- TRUNCATE TABLE `certificate_templates`;   -- uncomment if table exists
-- TRUNCATE TABLE `certificate_batches`;     -- uncomment if table exists

-- ── 2. INSTRUCTOR INTERFACE ──────────────────────────────────────────────────

-- 2a. Overview Section — summary cards derive from live counts;
--     clearing students / sections / reports resets those numbers.

-- 2b. Your Sections  +  My Classes  +  Class Rosters
TRUNCATE TABLE `enrollments`;   -- student-section associations
TRUNCATE TABLE `sections`;      -- section definitions (codes, instructors, rooms)

-- 2c. Submission Tracker — student submission logs
TRUNCATE TABLE `attendance`;    -- per-student attendance / submission records

-- 2d. Calendar of Activities — shares the `activities` table (already cleared)

-- 2e. Activity Plans — drafts, submitted, and approved plans
--     (already truncated in 1b above)

-- 2f. Accomplishment Reports — drafts and submitted reports
--     (already truncated in 1b above)

-- 2g. Announcements — all posted bulletins
TRUNCATE TABLE `announcements`;

-- ── 3. ROTC OFFICER INTERFACE ────────────────────────────────────────────────

-- 3a. Overview Section — stats derive from live counts in students/sections;
--     clearing those tables resets the dashboard cards automatically.

-- 3b. Calendar of Activities — shares the `activities` table (already cleared)

-- 3c. Platoon Management  +  Student / Cadet Rosters
--     ROTC cadets are stored in `students` (component = 'ROTC').
TRUNCATE TABLE `students`;       -- wipes ALL component students (CWTS, LTS, ROTC)

-- 3d. Assign Officer Section — officer rosters in `users` (already deleted in 1a)

-- 3e. Activity Designs — blueprints / proposals
--     These are stored in `activity_plans` (already truncated in 1b).
--     If you have a separate `activity_designs` table, add it here:
-- TRUNCATE TABLE `activity_designs`;    -- uncomment if table exists

-- 3f. Report Submission — file uploads, logs, submission histories
--     Covered by `accomplishment_reports` (already truncated in 1b).
--     If you store uploaded files in a dedicated table, add it here:
-- TRUNCATE TABLE `report_uploads`;      -- uncomment if table exists

-- ── 4. SHARED AUDIT / LOG TABLES ─────────────────────────────────────────────

-- Portal audit trail — keep only admin-tagged entries if any exist;
-- in the current schema no admin-specific entries are written here.
DELETE FROM `portal_audit_logs`
WHERE  `role` IS NULL
   OR  LOWER(`role`) IN ('coordinator','instructor','rotcofficer','rotc');

-- Legacy audit table (no admin-specific rows in the current schema)
TRUNCATE TABLE `audit_logs`;

-- Notifications — remove non-admin entries
DELETE FROM `notifications`
WHERE  `role` IS NULL
   OR  LOWER(`role`) NOT IN ('admin','administrator');

SET FOREIGN_KEY_CHECKS = 1;

-- =============================================================================
-- SECTION C — POST-WIPE VERIFICATION  (run immediately after Section B)
-- =============================================================================

-- C1. Admin accounts must still exist (expect 1+ rows)
SELECT id, full_name, email, role
FROM   `users`
WHERE  `role` = 'Admin';

-- C2. No instructor / officer accounts should remain
SELECT COUNT(*) AS non_admin_accounts_remaining
FROM   `users`
WHERE  `role` <> 'Admin';

-- C3. Every operational table must be empty
SELECT 'students'               AS tbl, COUNT(*) AS cnt FROM `students`
UNION ALL
SELECT 'sections',                       COUNT(*) FROM `sections`
UNION ALL
SELECT 'enrollments',                    COUNT(*) FROM `enrollments`
UNION ALL
SELECT 'attendance',                     COUNT(*) FROM `attendance`
UNION ALL
SELECT 'activity_plans',                 COUNT(*) FROM `activity_plans`
UNION ALL
SELECT 'accomplishment_reports',         COUNT(*) FROM `accomplishment_reports`
UNION ALL
SELECT 'activities',                     COUNT(*) FROM `activities`
UNION ALL
SELECT 'announcements',                  COUNT(*) FROM `announcements`;

-- =============================================================================
-- TABLES INTENTIONALLY NOT TOUCHED
-- =============================================================================
-- users          WHERE role = 'Admin'   — preserved by DELETE filter
-- migrations     — Laravel migration history
-- cache          — Laravel file/DB cache
-- cache_locks    — Laravel cache locks
-- jobs           — Laravel queue
-- job_batches    — Laravel queue batches
-- failed_jobs    — Laravel queue failures
-- =============================================================================
